name: Trivy Scan

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # daily at midnight
  workflow_call:
    inputs:
      image-ref:
        type: string
        description: Docker image ref to be scanned by Trivy
        required: false

env:
  DOCKER_BUILDKIT: "1"
  COSIGN_EXPERIMENTAL: "1"

# Add permissions at the workflow level
permissions:
  contents: read
  security-events: write

jobs:
  trivy-fs:
    name: Scan filesystem
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Add this permission
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Scan repo filesystem
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          scan-type: fs
          format: sarif
          output: trivy-fs-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@48ab28a6f5dbc2ac3de24cb2c1bc80a9572dd067 # v3.27.6
        if: always()
        with:
          sarif_file: trivy-fs-results.sarif

      - name: Display scan results (table format)
        if: cancelled() == false
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          scan-type: fs
          format: table

  trivy-image:
    name: Scan image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Add this permission
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Normalize image name
        id: normalize
        shell: bash
        env:
          IMAGE_REF: ${{ inputs.image-ref }}
        run: |
          if [ -z "$IMAGE_REF" ]; then
            IMAGE_REF=$(echo "${GITHUB_REPOSITORY/docker-/}" | tr '[:upper:]' '[:lower:]')
            if [[ "$GITHUB_REF_NAME" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              IMAGE_REF="$IMAGE_REF:${GITHUB_REF_NAME/v/}"
            elif [ "$GITHUB_REF_NAME" == "main" ]; then
              IMAGE_REF="$IMAGE_REF:latest"
            else
              BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" \
                | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]/-/g')
              IMAGE_REF="$IMAGE_REF:$BRANCH_NAME"
            fi
          fi
          echo "image-ref=$IMAGE_REF" | tee -a "$GITHUB_OUTPUT"

      - name: Scan image
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: ${{ steps.normalize.outputs.image-ref }}
          format: sarif
          output: trivy-image-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@48ab28a6f5dbc80a9572dd067 # v3.27.6
        if: always()
        with:
          sarif_file: trivy-image-results.sarif

      - name: Display scan results (table format)
        if: cancelled() == false
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          image-ref: ${{ steps.normalize.outputs.image-ref }}
          format: table